/**
 * Vector Compatibility Validation
 * 
 * Ensures that vector embeddings generated by different devices are compatible.
 * Critical for preventing silent data corruption in semantic search.
 * 
 * Design Decision: Hard fail on version mismatch (not silent fallback).
 * Rationale: Better to show clear error than have broken search.
 */

import * as tf from '@tensorflow/tfjs';

/**
 * Vector metadata stored with each PageDigest
 */
export interface VectorMetadata {
  /** TensorFlow.js version used to generate the embedding */
  tfVersion: string;
  
  /** Universal Sentence Encoder model version */
  useVersion: string;
  
  /** Backend used (webgl, cpu, wasm) */
  backend: string;
  
  /** Vector dimensions (should always be 512 for USE) */
  dimensions: number;
  
  /** Timestamp when vector was generated */
  generatedAt: number;
}

/**
 * Expected versions for this release
 * CRITICAL: These must match package.json exactly
 */
export const EXPECTED_VERSIONS = {
  tfjs: '4.22.0',
  use: '1.3.3',
  vectorDimensions: 512,
} as const;

/**
 * Validate vector metadata against expected versions
 * 
 * @param metadata - Vector metadata from remote device
 * @returns true if compatible, false otherwise
 * @throws Error with user-friendly message if incompatible
 */
export function validateVectorMetadata(metadata: VectorMetadata): boolean {
  const errors: string[] = [];
  
  // Check TensorFlow.js version
  if (metadata.tfVersion !== EXPECTED_VERSIONS.tfjs) {
    errors.push(
      `TensorFlow.js version mismatch: expected ${EXPECTED_VERSIONS.tfjs}, got ${metadata.tfVersion}`
    );
  }
  
  // Check USE version
  if (metadata.useVersion !== EXPECTED_VERSIONS.use) {
    errors.push(
      `Universal Sentence Encoder version mismatch: expected ${EXPECTED_VERSIONS.use}, got ${metadata.useVersion}`
    );
  }
  
  // Check dimensions
  if (metadata.dimensions !== EXPECTED_VERSIONS.vectorDimensions) {
    errors.push(
      `Vector dimension mismatch: expected ${EXPECTED_VERSIONS.vectorDimensions}, got ${metadata.dimensions}`
    );
  }
  
  // If any errors, throw with user-friendly message
  if (errors.length > 0) {
    const errorMessage = [
      '❌ Vector Incompatibility Detected',
      '',
      'Your devices are using different AI model versions, which will break semantic search.',
      '',
      'Details:',
      ...errors.map(e => `  • ${e}`),
      '',
      'Solution:',
      '  1. Update both devices to the latest BrainPlus version',
      '  2. Ensure both extensions are on the same version',
      '  3. Try syncing again',
      '',
      'For more info, visit: https://brainplus.dev/docs/sync-troubleshooting',
    ].join('\n');
    
    throw new Error(errorMessage);
  }
  
  return true;
}

/**
 * Get current vector metadata for this device
 */
export async function getCurrentVectorMetadata(): Promise<VectorMetadata> {
  await tf.ready();
  
  return {
    tfVersion: tf.version.tfjs,
    useVersion: EXPECTED_VERSIONS.use,
    backend: tf.getBackend(),
    dimensions: EXPECTED_VERSIONS.vectorDimensions,
    generatedAt: Date.now(),
  };
}

/**
 * Compare two vector metadata objects for compatibility
 * 
 * @param local - Local device metadata
 * @param remote - Remote device metadata
 * @returns Compatibility report
 */
export function compareMetadata(
  local: VectorMetadata,
  remote: VectorMetadata
): {
  compatible: boolean;
  warnings: string[];
  errors: string[];
} {
  const warnings: string[] = [];
  const errors: string[] = [];
  
  // Critical checks (hard errors)
  if (local.tfVersion !== remote.tfVersion) {
    errors.push(`TensorFlow.js version mismatch: ${local.tfVersion} vs ${remote.tfVersion}`);
  }
  
  if (local.useVersion !== remote.useVersion) {
    errors.push(`USE version mismatch: ${local.useVersion} vs ${remote.useVersion}`);
  }
  
  if (local.dimensions !== remote.dimensions) {
    errors.push(`Dimension mismatch: ${local.dimensions} vs ${remote.dimensions}`);
  }
  
  // Soft warnings (informational)
  if (local.backend !== remote.backend) {
    warnings.push(
      `Different backends: ${local.backend} vs ${remote.backend}. ` +
      `This may cause slight numerical differences.`
    );
  }
  
  return {
    compatible: errors.length === 0,
    warnings,
    errors,
  };
}

/**
 * Log vector compatibility check result
 */
export function logCompatibilityCheck(
  localMeta: VectorMetadata,
  remoteMeta: VectorMetadata
): void {
  const comparison = compareMetadata(localMeta, remoteMeta);
  
  console.log('='.repeat(60));
  console.log('Vector Compatibility Check');
  console.log('='.repeat(60));
  console.log(`Local:  TF ${localMeta.tfVersion} | USE ${localMeta.useVersion} | ${localMeta.backend}`);
  console.log(`Remote: TF ${remoteMeta.tfVersion} | USE ${remoteMeta.useVersion} | ${remoteMeta.backend}`);
  console.log('');
  
  if (comparison.errors.length > 0) {
    console.error('❌ INCOMPATIBLE:');
    comparison.errors.forEach(e => console.error(`  • ${e}`));
  } else {
    console.log('✅ COMPATIBLE');
  }
  
  if (comparison.warnings.length > 0) {
    console.warn('⚠️ Warnings:');
    comparison.warnings.forEach(w => console.warn(`  • ${w}`));
  }
  
  console.log('='.repeat(60));
}

/**
 * Validate that PageDigest has vector metadata
 * 
 * For backwards compatibility, old PageDigests may not have metadata.
 * In this case, we assume they were generated with current versions.
 */
export function ensureVectorMetadata(
  digest: any,
  defaultMetadata?: VectorMetadata
): VectorMetadata {
  if (digest.vectorMetadata) {
    return digest.vectorMetadata;
  }
  
  // Backwards compatibility: if no metadata, use defaults
  if (defaultMetadata) {
    return defaultMetadata;
  }
  
  // Assume current versions for legacy data
  console.warn(
    `PageDigest ${digest.pageId} missing vector metadata. ` +
    `Assuming current versions (may cause issues if from old extension).`
  );
  
  return {
    tfVersion: EXPECTED_VERSIONS.tfjs,
    useVersion: EXPECTED_VERSIONS.use,
    backend: 'webgl',
    dimensions: EXPECTED_VERSIONS.vectorDimensions,
    generatedAt: digest.timestamp || Date.now(),
  };
}

